
//EXERCÍCIO 1
CREATE TABLE R (at1 inT, at2 INT, at3 INT);

INSERT INTO R VALUES (12, 15, 5100); 
INSERT INTO R VALUES (13, NULL, 3500); 
INSERT INTO R VALUES (14, NULL, NULL);
INSERT INTO R VALUES (15, 12, NULL);

SELECT * FROM R WHERE (at2<12) OR (at3<3000)
SELECT * FROM R WHERE (at2>12) AND (at3>3000)
SELECT * FROM R WHERE (at2>12) OR NOT (at2>12)
SELECT * FROM R WHERE (NOT at2<at2) AND (at3>at2)
SELECT * FROM R WHERE (at2=at2) OR (NOT at3=at3)

//EXERCÍCIO 2
SELECT FUNC.Pnome, FUNC.Unome, DEPEN.Nome_dependente
FROM FUNCIONARIO AS FUNC INNER JOIN DEPENDENTE AS DEPEN
    ON FUNC.Cpf = DEPEN.Fcpf
